#!/bin/bash

if [ "$#" -eq 0 ]; then
  echo "Please supply a youtube link to convert to mp3"
  exit 1
fi

link=$1

youtube-dl --extract-audio --audio-format mp3 --verbose $link
echo "$link successfully converted"
